### ISSUE TITLE
JS reset option

### ISSUE THREAD

**Issue by imrohan22** [benfred/venn.js#117]
For dynamic data, if data for all sets are 0, it gives error. After that even if we pass values greater than 0, venn is not drawing. 
It works if we reset page and try again with data greater than 0.
![venn error](https://user-images.githubusercontent.com/14053375/35375002-5214bd7a-01cb-11e8-83c6-b53544ad09c5.JPG)

**Need facility to reset to default state.**

**Comment by benfred** [comment]
I realized I hadn't pushed the lastest version to gh-pages so the examples were running an old version. This should be fixed by this commit: https://github.com/benfred/venn.js/commit/88c63e0957e1191d30eeaaa3029246b3c53e5bbf

This should work here now http://benfred.github.io/venn.js/examples/dynamic.html
