### ISSUE TITLE
Here is cross of circles without cross numbers

### ISSUE THREAD

**Issue by alexeyrv** [benfred/venn.js#119]
Hello.
Thank for nice library. 
I hope I'm right if here is classical logic for Euler circles (Venn as special goal of Euler's circles).
But here is some problem with crossing of classes which have no crosses.

Arrays here are: A=4, B-10, C=7
Conditions: AB=4, AC=0, BC=4, ABC=0;
We have in result:
A out of B - but all A in the B
A and C crossed - but A and C have no cross value and here is enough space in B [ B - (AB + BC) = 2 ]

If I'm wrong clear it, please.
Have a nice coding!
Alex

Illustration here is:
![euler_circles_js at 2018-02-02 23 45 47](https://user-images.githubusercontent.com/3062541/35758313-b077069e-0873-11e8-975d-16fb7f9778d0.png)

**Comment by alexeyrv** [comment]
Hi again.
I installed Eulerr lib into RStudio and test the same situation.
It looks normal. 
Here is the result.

![euler in r repeated at 2018-02-03 00 19 59](https://user-images.githubusercontent.com/3062541/35759132-09b8ba8c-0878-11e8-904c-a1bb02bfe854.png)

Best wishes,
Alex

**Comment by benfred** [comment]
This package runs an optimization process - trying to find the best possible diagram given the inputs.

With the inputs you've given, the 'A' circle should be completely inside the 'B' circle with venn.js (since |A| is the same as |A∩B|).  venn.js attempts to do this, but fails since there isn't enough room for A to completely fit inside of B with the other constraints with the C set.

I think the inputs with eulerr might be referring to the disjoint set sizes (like the total size of A you are passing to euller is "A" + "A&B" + "A&C" = 8 in eulerr, versus only 4 when given to venn.js). This makes the eulerr not try to completely fit the A set inside of B - leading to the diagram you posted.

**Comment by alexeyrv** [comment]
Hey! I see it is in development progress.
Maybe you can see logic in Eulerr library in R Project CRAN.
If it is possible to see sources.

Wish you success.
BR, Alex

**Comment by alexeyrv** [comment]
It is a great job and thank you for a link to research paper.
