### ISSUE TITLE
some question about the Greedy Algorithm

### ISSUE THREAD

**Issue by Sweetdan** [benfred/venn.js#122]
why the three sets are more accurate than the two sets when generating initial layout with MDS alogorithm??

**Comment by Sweetdan** [comment]
Sorry, it should be the MDS alogorithm?

**Comment by benfred** [comment]
The MDS algorithm *should* be basically perfect with 2 sets as well - but I was running into some numerical stability issues with the SVD implementation I was using from numeric.js. I remember investigating and finding that certain inputs were getting NaN values from numeric.js (but passing the same values to the svd implementation in numpy worked fine). I didn't worry about it too much since I found better methods than the basic MDS algorithm
