### ISSUE TITLE
A∩B∩(!C) highlight

### ISSUE THREAD

**Issue by josephshum** [benfred/venn.js#43]
I want to start off by saying thank you for creating such an awesome library! I am looking to create visualizations that will allow me to light up A∩B∩(!C), like that shown in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/10375627/9399016/3730d9c8-4763-11e5-903b-893f69057c1f.png)

Any chance this is already in the works? Thanks again!

**Comment by benfred** [comment]
You're the second person to ask for this - https://github.com/benfred/venn.js/issues/23 has the original request.  

Its a little tricky to extend the existing approach because the areas might not be contiguous (like in that issue). 

I've wondered about using  SVG clipping to do this: like define the path as it is now and clip the other circles from it [like this ](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Clipping_and_masking). I think that might be the easiest way to do it, but I haven't had time to try =(
