### ISSUE TITLE
Can't recognize hover on triple intersection

### ISSUE THREAD

**Issue by ben-pr-p** [benfred/venn.js#45]
With the default order that the `g` elements are laid out, when I hover over the triple intersection center it shows that I'm hovering over one of the double intersections, shown here. (My mouse was not included in the screen shot, but it's in the triple intersection center.

<img width="1440" alt="screen shot 2015-09-30 at 4 50 55 pm" src="https://cloud.githubusercontent.com/assets/10324926/10204760/0799b850-6794-11e5-9310-e6f44755232c.png">

However, when I change the order of the `g` elements, it properly recognizes the hover. (mouse in the same place).

<img width="1440" alt="screen shot 2015-09-30 at 4 51 11 pm" src="https://cloud.githubusercontent.com/assets/10324926/10204793/29573b02-6794-11e5-9ef0-12854825b30a.png">

I could have Javascript rearrange the g elements after the fact, but that would be inelegant and may cause a temporary flash of the elements on the screen.

Would it be possible to have the `g` elements laid out in the number of sets order even if they are not all added at the same time (some are adding with an update)?

**Comment by benfred** [comment]
Is this after calling venn.sortAreas ? Calling this method in your mouseover handler should arrange everything in the proper order. I didn't do a static ordering because I wanted the current selection to be on top of the other items.

The file '[examples/intersection_tooltip.html](https://github.com/benfred/venn.js/blob/master/examples/intersection_tooltip.html)'  has an example of this working. I also wrote a blog post that used this with data that gets updated [http://www.benfrederickson.com/distance-metrics/](http://www.benfrederickson.com/distance-metrics/)

**Comment by ben-pr-p** [comment]
Nope, that fixed it!

Thanks for the prompt response!
