### ISSUE TITLE
Two set overlap sublable showing even when contained within three set overlap

### ISSUE THREAD

**Issue by ben-pr-p** [benfred/venn.js#48]
<img width="1440" alt="screen shot 2015-10-05 at 5 15 27 pm" src="https://cloud.githubusercontent.com/assets/10324926/10292339/067cd494-6b85-11e5-960f-78f149f52e42.png">

Here, you can see that the `1 opinions` is underneath `Test Platform 3`. There are actually 2 sublabels there – one for the intersection of `Test Platform 3` and `1`, and the other form `3` and `2`. 

I suppose what is needed is a recognition that `3` shares no elements with `2` that it doesn't also share with `1`, and vice versa. Their entire `<g>` elements could be deleted. 

It could be done by asking, "if there area of this intersection is fully contained within an intersection that has more sets, delete me".

What do you think?

**Comment by benfred** [comment]
So - there are a bunch of issues here, one of which is that maybe we should be hiding these areas.

Another issue is that the second '1 opinions' label is in the wrong location. https://github.com/benfred/venn.js/commit/049014118a486891f29a44d63faefccceb8f9d32 fixes so that the extra labels go into the appropriate place, which looks ok:

<img width="618" alt="screen shot 2015-10-05 at 10 33 46 pm" src="https://cloud.githubusercontent.com/assets/69536/10300947/092a629c-6bb2-11e5-9931-8e84e3934e9b.png">

There is another bug here with computing text centres that is triggered with only slightly different input though =(  Also, I think that the inner circle here should be centred. Will keep you posted.

**Comment by ben-pr-p** [comment]
It makes sense to me to hide them. Let me know what you'd like to me to do, I'm pretty familiar with the library at this point.

**Comment by benfred** [comment]
If you want to make the change to hide the areas that would be great! I could also get it done on the weekend maybe - lmk=)

**Comment by ben-pr-p** [comment]
Actually, 0490141 is working perfectly for me. I don't know if there are any other problems that hiding the unnecessary intersections would fix, but I'll wait until those manifest themselves to fix it. 

Thanks for the fix!

**Comment by ben-pr-p** [comment]
Woops – one more problem – so when it's full size it looks great:

<img width="1440" alt="good" src="https://cloud.githubusercontent.com/assets/10324926/10318288/138f1754-6c3f-11e5-9926-be761cb88e97.png">

However, when I make it smaller (in this case by bringing up the console), one of the `1 opinions` sublabels (there are 3 of them) go to the side:

<img width="1440" alt="bad" src="https://cloud.githubusercontent.com/assets/10324926/10318320/3a26b322-6c3f-11e5-80d9-2e30936d6a90.png">

This may be an additional instance of what you fixed in 0490141 – not sure.

Either way, hiding unnecessary `g` elements would fix both, so I'll see if I have time to do that soon.

**Comment by benfred** [comment]
Yeah - thats the other case I was talking about. 

The problem here is the fallback code in computeTextCentres is kinda dumb for intersection areas. Especially [this line]( https://github.com/benfred/venn.js/blob/049014118a486891f29a44d63faefccceb8f9d32/src/diagram.js#L339).

So, that areaStats structure has the intersection points and arcs for each area (as explained [in the 'exact solution' section of this post](http://www.benfrederickson.com/calculating-the-intersection-of-3-or-more-circles/) ).  

With your example here there are two points returned that have almost 0 distance between them, right on top of where the label is being drawn. I averaged those points and ignored the arcs - even though one arc is basically the entire circle. 

Hiding the unnecessary elements will hide the error obviously =)

**Comment by benfred** [comment]
This should be fixed with that last commit (at least the textCentre will be set appropiately - there will still be 3 identical overlapping elements here).

**Comment by ben-pr-p** [comment]
Placement works:
![almost fixed](https://cloud.githubusercontent.com/assets/10324926/10397254/0db44f3a-6e7d-11e5-9dd3-eaf238705580.jpg)

For some reason the triple overlap is not all the same sublabel, so it looks weird. I'll investigate more. Either way, hiding should still fix it.

**Comment by ben-pr-p** [comment]
It's a 3 on top of a 1 – the real count is 1.

**Comment by benfred** [comment]
I'm guessing that 'test platform 3' and 'test platform 1'  has size '3' - and the label for that is placed on top of the 1 there. Its the best location probably for that label, I think hiding it is really the only possible thing to do here.

**Comment by ben-pr-p** [comment]
Bug was on my end in calculating the size of the intersections – I gave A U B U C a size of 3 and A U B a size of 1. 

Still no need to implement hiding, but maybe it'll pop up again in the future.

Thanks for all your help!

**Comment by ben-pr-p** [comment]
![Uploading Screen Shot 2015-10-10 at 8.19.33 PM.png…]()

**Comment by ben-pr-p** [comment]
This did it! Option Three was fine.

```
hideUselessCircles () {
    var intersections = d3.selectAll('.venn-intersection');
    intersections.each(a => {
      intersections.each(b => {
        var selector = '[data-venn-sets="' + a.sets.join('_') + '"]';

        var isRedundant = ((a != b) && (a.sets.isSubsetOf(b.sets)) && (a.size <= b.size));

        d3.select(selector).classed('hide', isRedundant);
      });
    });
  }
```
