### ISSUE TITLE
No hover / click on inner circle when inside larger circle

### ISSUE THREAD

**Issue by ben-pr-p** [benfred/venn.js#49]
![bug](https://cloud.githubusercontent.com/assets/10324926/10319345/1f39dcec-6c44-11e5-9d67-04682ed819d4.jpg)

When I hover over an inner circle when it's completely contained within a larger one, it doesn't work.

Not quite sure what the error is since sortAreas is being called so it should recognize the intersection of the two circles on top of both of the independent circles.

Any ideas?

**Comment by benfred** [comment]
So - the problem is that when sortAreas is called, the 'relativeTo' is being set to Test Platform 2. This sets it on top when its being hovered over, and then its left on top afterwards.

Calling 'venn.sortAreas(div, null)' instead would put test platform 3 on top all the time, but also means that the current selection isn't on top (which looks worse in most situations depending on the styling).

I can think of two ways to fix:

1) Putting invisible svg path's on top of diagram, smallest first
Have an extra invisible svg path elements that mirrors the underlying venn diagram. Use these for mouseover / styling. Each element will be on top of the diagram, and Z order will be correct. But adds an extra layer of complexity.

2) Detecting when one area completely overlaps another in venn.sortAreas, and not putting it on top
This is pretty easy for circles (like above), but handling for intersection areas of 2+ sets is a little trickier.

**Comment by benfred** [comment]
So - I implemented a first pass at the second approach in the last commit. 

It works for the 1-circle case. I haven't tested on higher order intersections though, let me know if you see any issues with it there

**Comment by ben-pr-p** [comment]
Works – tested up to 3 overlapping circles with 1 inside all of them.
