### ISSUE TITLE
intuitive way to change fill colors.

### ISSUE THREAD

**Issue by Yahkob** [benfred/venn.js#53]
I think it would be good to have some sort of functionality maybe in the sets you pass to venn.js to have a way to use custom colors for venn sections something like: 
`{'sets': [0], 'label': 'Some Section', 'size': 16, style: 'Some style stuff here'},` or actually specify with css element you want `{'sets': [0], 'label': 'Some Section', 'size': 16, fill: 'Some style stuff here'},` . Right now its a pretty cumbersome process to change colors it feels too dirty to me to change through d3.select('g').style('...') the way I've implemented it is actually just changing the source which feels... dirtier to me :smile: 

I actually implemented some functionality where you can just pass fill/stroke to each set and that will set them at run time instead of after graph is rendered to eliminate repaints. If you're interested I could open a PR with my changes in. Also open to going the direction of having just a wildcard 'style' property in each set

**Comment by benfred** [comment]
So - I'd rather keep the data separate from the styling of the chart (personal preference really), but I agree that overriding the style in JS afterwards isn't optimal.

I added an option to turn off styling altogether, which means that you can style the diagram in CSS instead of JS. Example code is here: https://github.com/benfred/venn.js/blob/master/examples/css_styled.html
