### ISSUE TITLE
Overriding sorting of circles

### ISSUE THREAD

**Issue by Ellisthion** [benfred/venn.js#56]
The ~~greedyLayout~~ orientCircles function sorts the circles by size. My specific desire is to having it so circles A,B,C are always in that order clockwise, but overriding this is... problematic.

It's not possible to change the sorting without overriding the entire layout function, which (considering its smarts) basically means copy-pasting chunks of code with a small change.

It would be nice if there was either:
* An option to sort circles by their data ordering rather than size
* An option to set the sorting function, in a similar way to how the layout function can be entirely overriden

**Comment by benfred** [comment]
I think your issue here is with the 'normalizeSolution' code rather than the layout code, specifically in the ['orientateCircles' function code here](https://github.com/benfred/venn.js/blob/master/src/layout.js#L452)

 This code tries to axis align the biggest and second biggest set (as well as re-arrange disjoint clusters etc).  A demo + more information is here: http://benfred.github.io/venn.js/tests/normalization_test.html

The  'orientation' param (which is configurable)  affects which axis it tries aligning to. The default value is pi/2 which indicates to align along x-axis with biggest on the left, changing to "-Math.PI/2" uses x-axis with biggest on the right, changing to "Math.PI" puts largest at the bottom etc. 

I don't think its too hard to add an option to set a function that controls the sort order here - would be basically the same as the 'orientation' param thats already passed along.

**Comment by Ellisthion** [comment]
Right yes sorry; got mixed up, it is orientateCircles. Got lost as to what function I was looking at. :-) That method can't be directly overridden which makes it impractical to change etc etc.

The normalization is actually fantastic for my use case, but yep the orientation param doesn't quite do enough. :-)

**Comment by benfred** [comment]
Wired it in so you can do option 2, example usage here:

https://github.com/benfred/venn.js/blob/master/examples/orientation_order.html

**Comment by Ellisthion** [comment]
Wow that was quick! That's absolutely perfect, thanks! :-D
