### ISSUE TITLE
Truncated labels support

### ISSUE THREAD

**Issue by Yahkob** [benfred/venn.js#61]
Anything built in at this point to truncate long labels? I put in some external JS logic after calling `Venn.VennDiagram()`  to truncate strings based on the diameter of the circle and the label font size but it seems to bounce back and forth from the truncated string to the full label because of calculations in the actual venn.js library

**Comment by benfred** [comment]
Its probably hitting an issue with transitions and the text wrapping code - after the transition is over we potentially wrap the text of long labels (for an example, check out http://www.benfrederickson.com/distance-metrics/ and type in a longer artist name like 'Wolfgang Amadeus Mozart'). 

You can turn off this text wrapping by  going like
```
var chart = venn.VennDiagram()
    .wrap(false)
```

Alternatively, you could truncate the labels before passing as input (setting the 'label' property of the set inputs overrides using the set name, see http://benfred.github.io/venn.js/examples/venn_venn.html)

**Comment by Yahkob** [comment]
I just tried to set .wrap(false) when i call  `VennDiagram` but still think it may be doing some calculations and overwriting at some point. I was thinking about passing truncated labels as an input but I want them to be dynamically truncated using `getBBox` for some rough calculations. I have gotten it to work if I modify at the venn.js level

**Comment by Yahkob** [comment]
Pretty stumped, best solution that doesn't break I have found is to put it in the pathTween which is obviously not ideal :smile: @benfred

**Comment by tessaSAC** [comment]
I know Yakhob closed this issue, but in case anyone else finds it and like me has been struggling with a label overlapping issue (in my case a Venn diagram with a very large and very small circle), there was an alternative suggestion in #25 to de-overlap the labels instead of truncating.

I put together a [code sample](https://github.com/benfred/venn.js/issues/25#issuecomment-498820430) based on the suggestion written there.
