### ISSUE TITLE
Why did you choose  downhill simplex  method to optimize the lossFunction?

### ISSUE THREAD

**Issue by Sweetdan** [benfred/venn.js#93]
hi,
    I'm currently trying to implement venn diagrams with Canvas，and your code has given me a lot of inspiration , thanks for the good work. 
    I have a question which is mentioned in the title . What is the feature of this function that make you  choose the simplex method at last , why not any other method?
   My English is not very good, if there is anything wrong in my words please understand.
   looking forward to your reply.

**Comment by benfred** [comment]
I'm using the downhill simplex method for the last phase to fine to the solution. It should already have a decent approximation of the solution, from either the greedy or [constrained MDS](benfrederickson.com/better-venn-diagrams/) optimizers.

I'm mainly using the nelder-mead method since the loss function its optimizing is non-differentiable in spots (when circles are disjoint or completly overlapped). Even when circles aren't disjoint - calculating the derivative of the loss function didn't seem trivial: even figuring out the [how to exactly calculate the area of the intersection of 3+ circles](http://www.benfrederickson.com/calculating-the-intersection-of-3-or-more-circles/) was slightly involved.

So I wanted a derivative free optimizer to do the fine tuning step. Nelder-Mead is probably the simplest option here, though I did consider also using a [Bayesian Optimization](http://haikufactory.com/files/bayopt.pdf) scheme instead.

Hope this helps!

**Comment by Sweetdan** [comment]
Thanks , It helps me a lot.
